-- Script pour creer les utilisateurs

-- Utilisateur avec tous les droits (pour ETL et migrations)
CREATE USER ${DB_USER_WRITER} WITH PASSWORD '${DB_PASSWORD_WRITER}';
GRANT ALL PRIVILEGES ON DATABASE deputedex TO ${DB_USER_WRITER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER_WRITER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER_WRITER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER_WRITER};

-- Utilisateur en lecture seule (pour l'app React)
CREATE USER ${DB_USER_READER} WITH PASSWORD '${DB_PASSWORD_READER}';
GRANT CONNECT ON DATABASE deputedex TO ${DB_USER_READER};
GRANT USAGE ON SCHEMA public TO ${DB_USER_READER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_USER_READER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_USER_READER};